webserver:
  build: .
  links:
    - mysqlserver
  ports:
    - "80:80"
  volumes:
    - ./:/var/www
mysqlserver:
  image: mysql
  ports:
      - "3306:3306"
  environment:
     MYSQL_ROOT_PASSWORD: root